from __future__ import annotations

from os import PathLike

class LeafLabelMap:
    def num_labels(self) -> int: ...
    def get_label(self, index: int) -> str | None: ...
    def get_index(self, label: str) -> int | None: ...
    def labels(self) -> list[str]: ...
    def __repr__(self) -> str: ...

class CompactVertex:
    @property
    def index(self) -> int: ...
    def is_root(self) -> bool: ...
    def is_internal(self) -> bool: ...
    def is_leaf(self) -> bool: ...
    @property
    def label_index(self) -> int | None: ...
    @property
    def branch_length(self) -> float | None: ...
    @property
    def children(self) -> tuple[int, int] | None: ...
    @property
    def parent(self) -> int | None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class CompactTree:
    @property
    def name(self) -> str | None: ...
    def num_leaves(self) -> int: ...
    def num_vertices(self) -> int: ...
    def root_index(self) -> int: ...
    def vertex(self, index: int) -> CompactVertex: ...
    def vertices(self) -> list[CompactVertex]: ...
    def height(self) -> float: ...
    def total_branch_length(self) -> float: ...
    def to_newick(self, label_map: LeafLabelMap) -> str: ...
    def __repr__(self) -> str: ...

def parse_nexus_file(path: str | PathLike[str]) -> tuple[list[CompactTree], LeafLabelMap]: ...
